- id: avalanche_score
  alias: avalanche_score
  trigger:
  - platform: event
    event_type: nhl_goal
    event_data:
      goal_tracked_team: true
  condition: []
  action:
  - service: system_log.write
    data_template:
      message: 'Aves Score Automation Trigger({{ as_timestamp(now()) }}): {{ trigger
        }} '
      level: warning
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  - delay: '0.2'
  - service: homeassistant.toggle
    data: {}
    entity_id: group.nhl_lights
  initial_state: true
  mode: single
- id: '1610683069089'
  alias: Push to phone
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_one_a2005
    data:
      title: Check this out!
      message: Something happened at home!
      data:
        push:
          category: alarm
        action_data:
          entity_id: switch.eb06e894f64866e076kdao
          my_custom_data: foo_bar
  mode: single
- id: set_theme
  alias: Set Home Assistant Theme on Start
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: frontend.set_theme
    data:
      name: ios-dark-mode
  mode: single
- alias: Perform Auto Backup
  trigger:
    platform: time_pattern
    hours: /3
  action:
    service: auto_backup.snapshot_partial
    data_template:
      name: 'AutoBackup: {{ now().strftime(''%a, %-I:%M %p (%d/%m/%Y)'') }}'
      addons:
      - core_mariadb
      - core_mosquitto
      folders:
      - homeassistant
      - share
      - ssl
      keep_days: 2
  id: 5b59be520ac340168ae5457813cec372
- alias: Perform Daily Backup
  trigger:
    platform: time
    at: 02:30:00
  condition:
    condition: time
    weekday:
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: 'DailyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
      keep_days: 7
  id: 0488c83c127a4845994736f9fa9eb4a8
- alias: Perform Weekly Backup
  trigger:
    platform: time
    at: 02:30:00
  condition:
    condition: time
    weekday:
    - mon
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: 'WeeklyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
      keep_days: 28
  id: 3ec6cfbb570941639d833212ddbb903e
- id: '1612306599523'
  alias: 'TV Room Button: Single Click'
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:12:4b:00:21:35:ac:5b
  - platform: event
    event_type: esphome.button_click
    event_data:
      entity: tv_room_side_table
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 5c:02:72:ff:fe:c3:cc:55
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "toggle" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 4 }}'
      sequence:
      - service: homeassistant.toggle
        entity_id: group.tv_room_single_click
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "on" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 3 }}'
      sequence:
      - service: homeassistant.toggle
        data: {}
        entity_id: group.tv_room_double_click
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "off" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 1 }}'
      sequence:
      - service: homeassistant.turn_off
        data: {}
        target:
          entity_id:
          - group.tv_room_single_click
          - group.tv_room_double_click
          - light.pantry_light
    default: []
  mode: single
- id: Master Bathroom Buttons
  alias: Master Bathroom Button
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 58:8e:81:ff:fe:1c:e8:55
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 5c:02:72:ff:fe:a1:38:3e
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: 50ebe23b85300387830b55cc3e744197
        entity_id: light.master_bath_color_light
        domain: light
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "off" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 3 }}'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bathroom_lights_off
    - conditions:
      - condition: time
        after: '23:30'
        before: '7:00'
      - condition: device
        type: is_off
        device_id: 50ebe23b85300387830b55cc3e744197
        entity_id: light.master_bath_color_light
        domain: light
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "off" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 3 }}'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bath_lights_night
    - conditions:
      - condition: device
        type: is_off
        device_id: 50ebe23b85300387830b55cc3e744197
        entity_id: light.master_bath_color_light
        domain: light
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 3 }}'
        - condition: template
          value_template: '{{ trigger.event.data.command  == "off" }}'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bathroom_ligths_day
    - conditions:
      - condition: device
        type: is_off
        device_id: 50ebe23b85300387830b55cc3e744197
        entity_id: light.master_bath_color_light
        domain: light
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "on" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 2 }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 1 }}'
      sequence:
      - service: scene.turn_on
        data: {}
        entity_id: scene.master_bathroom_ligths_day
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ trigger.event.data.command  == "on" }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 2 }}'
        - condition: template
          value_template: '{{ trigger.event.data.endpoint_id  == 1 }}'
      sequence:
      - service: scene.turn_on
        data: {}
        entity_id: scene.master_bathroom_lights_off
    default: []
  - service: system_log.write
    data:
      level: warning
      message: Trigger:{{ trigger.event.data.command }}
  mode: single
- id: '1612757569353'
  alias: Master Bathroom Door Lights
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:03:ce:be:13
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.args.value == false }}'
      - condition: time
        after: '23:30'
        before: '7:00'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bath_lights_night
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.args.value == false }}'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bathroom_ligths_day
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.args.value == true}}'
      sequence:
      - service: scene.turn_on
        entity_id: scene.master_bathroom_lights_off
  mode: single
- id: '1615524460190'
  alias: Office 4-Button Switch
  description: ''
  use_blueprint:
    path: homeassistant/tuya_4_switch.yaml
    input:
      tuya_4button_scene_switch: 39a9f4653dea97b165d696e02dec86e4
      button_one_short_press:
      - service: homeassistant.toggle
        target:
          entity_id:
          - group.plant_lights
          - group.plant_nursery_lights
      button_one_double_press:
      - service: homeassistant.turn_on
        target:
          entity_id:
          - group.plant_lights
          - group.plant_nursery_lights
      button_three_short_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.office_lights
      button_four_short_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.front_yard_lights
      button_three_double_press:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.office_lights
      button_three_long_press:
      - service: light.turn_off
        target:
          entity_id: light.office_lights
      button_four_double_press:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.front_yard_lights
      button_four_long_press:
      - service: light.turn_off
        target:
          entity_id: light.front_yard_lights
      button_one_long_press:
      - service: homeassistant.turn_off
        target:
          entity_id:
          - group.plant_lights
          - group.plant_nursery_lights
- id: '1615525388857'
  alias: Turn on office lights at dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.office_lights
  mode: single
- id: 'delivery_coming'
  alias: Delivery Complete - Turn Porch Light Red
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.noco_nosh
    to: delivery_coming
  condition: []
  action:
  - scene: scene.front_delivery
  mode: single
- id: 'delivery_complete'
  alias: Delivery Complete - Turn Porch Light White
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.noco_nosh
    to: no_deliveries
  condition: []
  action:
  - scene: scene.front_white
  mode: single
- id: '1615690939113'
  alias: TV Room 4 Buttons
  description: Only for bottom right button. Others are covered with TV Single Click
    (or whatever)
  use_blueprint:
    path: homeassistant/tuya_4_switch.yaml
    input:
      tuya_4button_scene_switch: 57acf2649f5d0d55d239f33b8f5a4874
      button_two_short_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.pantry_light
      button_two_double_press:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.pantry_light
      button_two_long_press:
      - service: light.turn_off
        target:
          entity_id: light.pantry_light
