substitutions:
  name: kitchen_back_mmm
  friendly_name: Kitchen Back mm
packages:
  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret athom-presence-sensor-encryption


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
