esphome:
  name: "bedroom-main-ble-proxy"
  friendly_name: Bedroom (Main) BLE Proxy

#esphome:
#  name: ${name}
#  friendly_name: ${friendly_name}
#  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

#esp32:
#  board: m5stack-core-esp32
#  framework:
#    type: arduino

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf
    version: 5.1.1
    platform_version: 6.4.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom-main-ble-proxy-encryption 

ota:
  password: !secret bedroom-main-ble-proxy-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    

#improv_serial:

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true
    interval: 1000ms # default 320ms. Time spent per adv channel
    window: 900ms # default 30ms. Time spent listening during interval.

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
