substitutions:
  name: everything-presence-one-f98b78
  friendly_name: Kitchen mmWave
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one-ble.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret everything-presence-one-encryption


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
