#!/bin/sh
# Generated by aurora@aurora-smart-home (home-assistant skill)
# https://github.com/tonylofgren/aurora-smart-home
#
# Save a base64-encoded label preview PNG under /config/www/labels/<subdir>/.
#
# Invoked by shell_command.save_label_preview with three plain arguments:
#   $1 = subdir  (environment name, sanitized by script.print_label)
#   $2 = filename (e.g. preview.png, sanitized by script.print_label)
#   $3 = base64-encoded PNG bytes
#
# Home Assistant executes templated shell commands WITHOUT a shell (no pipes,
# redirects, or ~ expansion, and only text after the first space may be
# templated), so all shell syntax lives here instead of configuration.yaml.
set -eu

subdir="${1:-default}"
filename="${2:-preview.png}"
b64="${3:-}"

if [ -z "${b64}" ]; then
    echo "save_label_preview: no base64 payload" >&2
    exit 1
fi

dir="/config/www/labels/${subdir}"
mkdir -p "${dir}"
printf '%s' "${b64}" | base64 -d > "${dir}/${filename}"
