# AirGradient Pro V3.3 - V4.2
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "airgradient-porch"
  friendly_name: "Airgradient Porch"
  name_add_mac_suffix: "false"  # Must have quotes around value

# Enable Home Assistant API
api:

ota:  # Add password as desired
  platform: esphome
  # password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-pro.yaml
  import_full_config: false

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_d1_mini_board.yaml
  captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  #temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht40.yaml
  temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht30.yaml
  display: github://MallocArray/airgradient_esphome/packages/display_sh1106_single_page.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_d1_mini.yaml
  config_button: github://MallocArray/airgradient_esphome/packages/config_button.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
# I don't think it has this sensor, but validation fails if I remove it. So just hiding the sensors in HA.
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  
binary_sensor:
  - id: !extend config_button
    pin:
      number: D7