substitutions:
  name: "dinning-room-mm"
  room: "dinning-room"
  friendly_name: "Dinning Room mmWave"
packages:
  #athom.smart-plug-v2: github://EverythingSmartHome/everything-presence-one/everything-presence-one-st.yaml@1.1.8
  athom.smart-plug-v2: github://everythingsmarthome/presence-one/everything-presence-one-ble.yaml@v1.2.3
  #ble-tracking: github://EverythingSmartHome/everything-presence-one/common/bluetooth-base.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false


# Enable Home Assistant API
api:
  encryption:
    key: !secret dining-room-mm-encryption

ota:
  - platform: esphome
    password: !secret dining-room-mm-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1000ms # default 320ms. Time spent per adv channel
    window: 900ms # default 30ms. Time spent listening during interval.