substitutions:
  name: dining-room-mm-athom
  friendly_name: Dining Room mm Athom
packages:
  Athom_Technology.Athom_Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: !secret dining-room-mm-athom-encryption

esp8266:
  board: esp8285
  restore_from_flash: true

web_server: {}

ota:
  - platform: esphome

number:
  - id: !extend Farthest_Detection
    min_value: 0.1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .spencerslab.com
  #manual_ip:
    # Set this to the IP of the ESP
  #  static_ip: 10.0.3.100
  #  gateway: 10.0.3.1
  #  subnet: 255.255.255.0
