substitutions:
  system: water-supply-01-nutrients
  system_friendly: Water Supply 01 (Nutrients)

packages:
  package-core-device: !include package-core-device.yaml
  package-sp10: !include f01-package-ss30.yaml
