esphome:
  name: generic-esp32
  friendly_name: generic-esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret generic-esp32-encryption

ota:
  password: !secret generic-esp32-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
