substitutions:
  name: "kitchen-mm"
  room: "kitchen"
  friendly_name: "Kitchen mmWave"
packages:
  athom.epo-ble: github://everythingsmarthome/presence-one/everything-presence-one-ble.yaml@v1.2.3
esphome:
  name: ${name}
  name_add_mac_suffix: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret kitchen-mm-encryption

ota:
  - platform: esphome
    password: !secret kitchen-mm-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Mm Fallback Hotspot"
    password: "G7m2rksthdsf"

captive_portal:
esp32_ble_tracker:
  scan_parameters:
    interval: 1000ms # default 320ms. Time spent per adv channel
    window: 900ms # default 30ms. Time spent listening during interval.
