substitutions:
  name: "master-bathroom-mm"
  room: "master-bathroom"
packages:
  athom.smart-plug-v2: github://EverythingSmartHome/everything-presence-one/everything-presence-one-st.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  
# Enable Home Assistant API
api:
  encryption:
    key: "bjrq2QoJvI4/5Aqljx0PpvPkN5SIahV6DufiYjFRl4g="

ota:
  password: "ee5931b1a26977ee71e29394a91d287a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master-Bathroom-Mm"
    password: "xFwgAhKFFWmb"

captive_portal:
    