substitutions:
  system: master-bedroom-closet-power
  system_friendly: Master Bedroom Closet Power

packages:
  package-core-device: !include package-core-device.yaml
  package-sp10: !include package-ss30.yaml
