substitutions:
  system: network-accessories-power
  system_friendly: Network Accessories Power

packages:
  package-core-device: !include package-core-device.yaml
  package-sp10: !include package-ss30.yaml