substitutions:
  system: power_monitor_master_bedroom
  system_friendly: Master Bedroom Power Monitor

packages:
  package-core-device: !include package-core-device.yaml
  package-sp20: !include package-sp20.yaml
