substitutions:
  system: power_monitor_bird_bath
  system_friendly: Bird Bath Power Monitor

packages:
  package-core-device: !include package-core-device.yaml
  package-sp20: !include package-sp20.yaml
