substitutions:
  name: tv-room-ble-proxy
  friendly_name: TV Room BLE Proxy
packages:
#  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atomS3.yaml@main
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atomS3.yaml@a53600f983e042480e729dea1c5843abe440f6c6
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
#esp32:
  #board: m5stack-atoms3
  #variant: esp32s3
  #framework:
  #  type: esp-idf
  #  version: 5.1.1
  #  platform_version: 6.4.0

api:
  encryption:
    key: !secret tv-room-ble-proxy-encryption

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret tv-room-ble-proxy-ota

captive_portal:
    

#improv_serial:
esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true
    interval: 1000ms # default 320ms. Time spent per adv channel
    window: 900ms # default 30ms. Time spent listening during interval.

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic