substitutions:
  system: tv_room_power_big_chair
  system_friendly: TV Room Power Big Chair

packages:
  package-core-device: !include package-core-device.yaml
  package-sp10: !include package-ss30.yaml
