esphome:
  name: water-supply-01-ir
  friendly_name: water-supply-01-ir

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret water-supply-01-ir-encryption

ota:
  - platform: esphome
    password: !secret water-supply-01-ir-ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: template
    name: Shaker Stop
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0x004A
          #address: 0xFF00
          #command: 0xB54A
  - platform: template
    name: Shaker Start
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0x0003

esp8266:
  board: esp8285
  restore_from_flash: true

remote_receiver:
  pin:
    number: GPIO5
    inverted: true
  dump: all # Dumps received codes to logs.

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

output:
  - platform: gpio
    pin: GPIO12
    id: gpio_12
  - platform: gpio
    pin: GPIO13
    id: gpio_13

switch:
  - name: Shaker
    platform: template
    turn_on_action: 
        - remote_transmitter.transmit_pioneer:
            rc_code_1: 0x0003
    turn_off_action:
        - remote_transmitter.transmit_pioneer:
            rc_code_1: 0x004A
            #address: 0xFF00
            #command: 0xB54A

  - name: "Top LED"
    id: led_top
    platform: output
    output: gpio_12
  - name: "Middle LED"
    id: led_middle
    platform: output
    output: gpio_13

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
      inverted: true
    name: Bottom Button
    on_press:
      then:
        - switch.toggle:
            id: led_middle
        - delay: 2s
        - switch.toggle:
            id: led_top


