#######################################################################################################################
## Package - Unavailable Entities Sensor - GROUP VERSION
## Count and list of entities with state of unavailable, unknown, or none (null)
##
## state: number of unavailable entities
## attributes:
##   entities: list of unavailable entity ids
##
## NOTES:
##  - Home Assistant v0.117+ is required
##  - This sensor updates once per minute.  State changes may take up to one minute to register.
##  - Home Assistant does not have to restarted to use this sensor.  Just reload Localizations & Customizations and Group Entities.
#######################################################################################################################

## This is the original version of the original Unavailable Entities Sensor Gist
## This version uses the ignored_entities group to declare ignored entities.  Each individual entity must be declared in the group.

## The updated version which uses custom attributes and allows ignored entities by domain and glob, and whitelisting entities is at
## https://gist.github.com/jazzyisj/0dd08334fc0a09984496bef5da9ec962

## REQUIRED this is the template sensor
sensor:
  - platform: template
    sensors:
      unavailable_entities:
        friendly_name: Unavailable Entities
        unit_of_measurement: entities
        icon_template: "{{ 'mdi:check-circle' if is_state('sensor.unavailable_entities','0') else 'mdi:alert-circle' }}"
        value_template: >
          {{ states|selectattr('state','in',['unavailable','unknown', 'nan'])|rejectattr('domain','eq','group')
            |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|list|count }}
        attribute_templates:
          entities: >
            {{ states|selectattr('state','in',['unavailable','unknown', 'nan'])|rejectattr('domain','eq','group')
                |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='entity_id')|list }}

          # Make sure the sensor is updated every minute. Grafana alerts depend on this.
          update_every_minute: >
            {{ now().minute }}


# REQUIRED add any entities you do not with to monitor in this group
# this group MUST exist even if is empty for sensor template to render
group:
  ignored_entities:
    entities:
      - binary_sensor.updater
