#######################################################################################################################
## Package - Unavailable Entities Sensor - GROUP VERSION
## Count and list of entities with state of unavailable, unknown, or none (null)
##
## state: number of unavailable entities
## attributes:
##   entities: list of unavailable entity ids
##
## NOTES:
##  - Home Assistant v0.117+ is required
##  - This sensor updates once per minute.  State changes may take up to one minute to register.
##  - Home Assistant does not have to restarted to use this sensor.  Just reload Localizations & Customizations and Group Entities.
#######################################################################################################################

automation:
  - id: delivery_coming
    alias: Delivery Complete - Turn Porch Light Red
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.noco_nosh
      to: delivery_coming
    condition: []
    action:
    - scene: scene.front_delivery
    mode: single
  - id: delivery_complete
    alias: Delivery Complete - Turn Porch Light White
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.noco_nosh
      to: no_deliveries
    condition: []
    action:
    - scene: scene.front_white
    mode: single
  - alias: 'House Lights: Cooking'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 4_single
    mode: single
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.cooking
        metadata: {}
  - alias: 'House Lights: Bright'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 1_single
    mode: single
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.house_mode_bright
        metadata: {}
  - alias: 'House Lights: Party'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 2_single
    mode: single
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.house_mode_party
        metadata: {}
  - alias: 'House Lights: Mood'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 4_double
    mode: single
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.house_mode_mood
        metadata: {}
  - alias: 'House Lights: TV'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 3_single
    mode: single
    condition: []
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.house_mode_tv
        metadata: {}
  - alias: 'House Lights: Couch'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 3_double
    mode: single
    condition: []
    action:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.tv_room_side_table_power_relay_4
  - alias: 'House Lights: Reset'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 2_double
    mode: single
    condition: []
    action:
      - service: automation.trigger
        data: {}
        target:
          entity_id: automation.lights_restore_default_colors
  - alias: 'House Lights: Office Lights'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: afde4e1e4b5130d838bd342d10f3c923
      type: action
      subtype: 1_double
    mode: single
    condition: []
    action:
      - service: light.toggle
        data:
          brightness_pct: 89
        target:
          area_id: office
  - id: '1661005890182'
    alias: 'Lights: Restore Default Colors'
    description: ''
    trigger: []
    condition: []
    action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
        - light.office_flipper_switch
        - light.hall_lights
        - light.bathroom_main_lights
        - light.tv_room_side_table_light
        - light.hall_main_lights
        - light.grow_room_lights
        - light.porch_lights
        - light.dining_room_game_corner_light_light
        area_id:
        - dining_room
        - tv_room
        - office
    - service: light.toggle
      data: {}
      target:
        entity_id:
        - light.kitchen_lights
        - light.bedroom_main_lights
    - service: light.toggle
      data: {}
      target:
        entity_id:
        - light.kitchen_lights
        - light.bedroom_main_lights
    - service: scene.turn_on
      target:
        entity_id: scene.default_light_colors
      metadata: {}
    - service: scene.turn_on
      target:
        entity_id: scene.default_color_lights_off
      metadata: {}
    mode: single
  - id: '1661008795175'
    alias: Hall Status
    description: ''
    trigger:
    - platform: state
      entity_id:
      - binary_sensor.contact_front_lock
    condition: []
    action:
    - if:
      - condition: state
        entity_id: binary_sensor.contact_front_lock
        state: 'on'
      then:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.hall_lights
      else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.hall_lights
    mode: single