#######################################################################################################################
## Package - Unavailable Entities Sensor - GROUP VERSION
## Count and list of entities with state of unavailable, unknown, or none (null)
##
## state: number of unavailable entities
## attributes:
##   entities: list of unavailable entity ids
##
## NOTES:
##  - Home Assistant v0.117+ is required
##  - This sensor updates once per minute.  State changes may take up to one minute to register.
##  - Home Assistant does not have to restarted to use this sensor.  Just reload Localizations & Customizations and Group Entities.
#######################################################################################################################

automation:
  - id: '1712981375915'
    alias: 'Bedroom Main: Toggle Lights'
    description: ''
    trigger:
    # Button
    - platform: device
      domain: mqtt
      device_id: 327a85af123e9a975cfb3ef53814160f
      type: action
      subtype: single
    # Disk 
    - platform: device
      domain: mqtt
      device_id: 80658f61524311c7df4dae373f78b535
      type: action
      subtype: toggle
    condition: []
    action:
      - service: light.toggle
        data: {}
        target:
          area_id: bedroom_main
    mode: single
  - alias: 'Bedroom Main: Presense Hold'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 327a85af123e9a975cfb3ef53814160f
      type: action
      subtype: double
    condition: []
    action:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.area_presence_hold_main_bedroom
    mode: single
  - id: '1712981375914'
    alias: 'Bedroom Main: Turn On Lights'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 80658f61524311c7df4dae373f78b535
      type: action
      subtype: brightness_up_click
    condition: []
    action:
    - service: light.turn_on
      target:
        area_id: bedroom_main
      data: {}
    mode: single
  - id: '1712981431951'
    alias: 'Bedroom Main: Turn Off Lights'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 80658f61524311c7df4dae373f78b535
      type: action
      subtype: brightness_down_click
    condition: []
    action:
    - service: light.turn_off
      metadata: {}
      data: {}
      target:
        area_id:
        - bathroom_main
        - closet_bedroom_main
        - bedroom_main
        - hall
    mode: single
  - id: '1712982464266'
    alias: 'Bedroom Main: Set Day Mode'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 80658f61524311c7df4dae373f78b535
      type: action
      subtype: brightness_up_hold
    condition: []
    action:
    - service: input_select.select_option
      metadata: {}
      data:
        option: Day
      target:
        entity_id: input_select.house_mode
    mode: single
  - id: '1712982502193'
    alias: 'Bedroom Main: Set Night Mode'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 80658f61524311c7df4dae373f78b535
      type: action
      subtype: brightness_down_hold
    condition: []
    action:
    - service: input_select.select_option
      metadata: {}
      data:
        option: Night
      target:
        entity_id: input_select.house_mode
    mode: single
