#######################################################################################################################
## Package - Unavailable Entities Sensor - GROUP VERSION
## Count and list of entities with state of unavailable, unknown, or none (null)
##
## state: number of unavailable entities
## attributes:
##   entities: list of unavailable entity ids
##
## NOTES:
##  - Home Assistant v0.117+ is required
##  - This sensor updates once per minute.  State changes may take up to one minute to register.
##  - Home Assistant does not have to restarted to use this sensor.  Just reload Localizations & Customizations and Group Entities.
#######################################################################################################################

automation:
  - alias: 'TV Room: DirecTV (Source)'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 4 = Top Left
      subtype: 4_single
    mode: single
    condition: []
    action:
      - service: media_player.turn_on
        data: {}
        target:
          area_id: tv_room
      - service: media_player.select_source
        target:
          area_id: tv_room
        data:
          source: HDMI-1
  - alias: 'TV Room: Media Player (Source)'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 3 = Top Right 
      subtype: 3_single
    mode: single
    condition: []
    action:
      - service: media_player.turn_on
        data: {}
        target:
          area_id: tv_room
      - service: media_player.select_source
        data:
          source: HDMI-2
        target:
          area_id: tv_room
  - alias: 'TV Room: Switch (Source)'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 1 = Bottom left
      subtype: 1_single
    mode: single
    condition: []
    action:
      - service: media_player.turn_on
        data: {}
        target:
          area_id: tv_room
      - service: media_player.select_source
        target:
          area_id: tv_room
        data:
          source: HDMI-3
  - alias: 'TV Room: Couch (Source)'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 1 = Bottom left
      subtype: 1_double
    mode: single
    condition: []
    action:
      - service: media_player.turn_on
        data: {}
        target:
          area_id: tv_room
      - service: media_player.select_source
        data:
          source: HDMI-4
        target:
          area_id: tv_room
  - alias: 'TV Room: Turn Off'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 4 = Top Left
      subtype: 4_double
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 3 = Top Right 
      subtype: 3_double
    mode: single
    condition: []
    action:
      - service: media_player.turn_off
        data: {}
        target:
          area_id: tv_room
  - alias: 'TV Room: Mute'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 1 = Bottom left
      subtype: 2_single
    mode: single
    condition: []
    action:
      - service: automation.trigger
        data: {}
        target:
          entity_id: automation.tv_automation_mute
  - alias: 'TV Room: Unmute'
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 9edc57d84dc63ad3e90e3fa6cf59795f
      type: action
      # 2 = Bottom Right
      subtype: 2_double
    mode: single
    condition: []
    action:
      - service: automation.trigger
        data: {}
        target:
          entity_id: automation.tv_automation_unmute 
